server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zixishi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    password:
    port: 6379
mybatis:
  mapper-locations: com.zixishi.zhanwei.mapper/*.xml
  type-aliases-package: com.zixishi.zhanwei.model

